Import new versions for packages in xapi-project/xs-opam
ocaml/opam-repository pull request #17810
Opened 2020-12-11 11:56 UTC by psafont

Not all packages are being updated, but it's a nice chunk. The rest are more difficult to import as they aren't tagged by version.

I expect some changes to be needed before merging, as the quality of the metadata is not as good as the default repo.

2020-12-11 12:07 UTC, mseri requested changes
Thanks. I only looked briefly, surely we need to fix the omnipresent `build` tag, if anything else is needed (like lower bounds on ocam) will be clearer after the CI runs

2020-12-11 12:07 UTC, mseri commented on packages/cdrom/cdrom.0.9.4/opam
> +  "dune" {build}
```suggestion
  "dune" {>= "1.4"}
```

2020-12-11 12:07 UTC, mseri commented on packages/crc/crc.2.1.0/opam
> +  "dune"
```suggestion
  "dune" {>= "1.4"}
```

2020-12-11 12:07 UTC, mseri commented on packages/dlm/dlm.0.3.1/opam
> +  "dune" {build & >= "1.4"}
```suggestion
  "dune" {>= "1.4"}
```

2020-12-11 12:07 UTC, mseri commented on packages/ezxenstore/ezxenstore.0.4.1/opam
> +  "dune" {build & >= "1.4"}
```suggestion
  "dune" {>= "1.4"}
```

2020-12-11 12:07 UTC, mseri commented on packages/fd-send-recv/fd-send-recv.2.0.1/opam
> +  "dune" {build}
```suggestion
  "dune" {>= "1.4"}
```

2020-12-11 12:07 UTC, mseri commented on packages/nbd/nbd.4.0.2/opam
> +  "dune" {build}
```suggestion
  "dune" {>= "1.4"}
```

2020-12-11 12:07 UTC, mseri commented on packages/netlink/netlink.0.3.4/opam
> +  "dune" {build}
```suggestion
  "dune" {>= "1.4"}
```

2020-12-11 12:07 UTC, mseri commented on packages/xapi-backtrace/xapi-backtrace.0.7/opam
> +  "dune" {build}
```suggestion
  "dune" {>= "1.4"}
```

2020-12-11 12:07 UTC, mseri commented on packages/xapi-inventory/xapi-inventory.1.2.1/opam
> +  "dune" {build}
```suggestion
  "dune" {>= "1.4"}
```

2020-12-11 12:07 UTC, mseri commented on packages/xapi-inventory/xapi-inventory.1.2.1/opam
> +  "ocamlfind" {build}
Is ocamlfind still needed?

2020-12-11 12:07 UTC, mseri commented on packages/xapi-rrd/xapi-rrd.1.8.1/opam
> +  "dune" {build & >= "1.4.0"}
```suggestion
  "dune" {>= "1.4"}
```

2020-12-11 12:10 UTC, psafont commented on packages/xapi-inventory/xapi-inventory.1.2.1/opam
> +  "ocamlfind" {build}
It's used for `./configure`

2020-12-11 12:45 UTC, camelus commented
Commit: 4e3bb664f53938b6af4a4110ed334ad4007df5c1

@psafont has posted 2 contributions.

##### :sunny: All lint checks passed <small>4e3bb664f53938b6af4a4110ed334ad4007df5c1</small>

* These packages passed lint tests: `cdrom.0.9.4`, `crc.2.1.0`, `dlm.0.3.1`, `ezxenstore.0.4.1`, `fd-send-recv.2.0.1`, `nbd.4.0.2`, `netlink.0.3.4`, `xapi-backtrace.0.7`, `xapi-inventory.1.2.1`, `xapi-rrd.1.8.1`


---


##### :sun_behind_small_cloud: Installability check (+9)

* new installable packages (9): `cdrom.0.9.4` `crc.2.1.0` `dlm.0.3.1` `ezxenstore.0.4.1` `fd-send-recv.2.0.1` `nbd.4.0.2` `netlink.0.3.4` `xapi-backtrace.0.7` `xapi-rrd.1.8.1`
* new **broken** packages (1): `xapi-inventory.1.2.1`

2020-12-11 21:54 UTC, mseri requested changes
A few more changes, the remaining errors seems fine (missing or old C deps, timeouts, ...)

2020-12-11 21:54 UTC, mseri commented on packages/xapi-stdext-std/xapi-stdext-std.4.14.0/opam
> +  "ocaml"
```suggestion
  "ocaml" {>= "4.08"}
```
Uses `List.filter_map`

2020-12-11 21:54 UTC, mseri commented on packages/xapi-inventory/xapi-inventory.1.2.1/opam
> +  "ocaml"
```suggestion
  "ocaml" {>= "4.08"}
```
Uses `List.filter_map`

2020-12-11 21:54 UTC, mseri commented on packages/xapi-stdext-unix/xapi-stdext-unix.4.14.0/opam
> +  "ocaml"
```suggestion
  "ocaml" {>= "4.08"}
```
Uses `List.filter_map`

2020-12-11 21:54 UTC, mseri commented on packages/xapi-rrd/xapi-rrd.1.8.2/opam
> +  "ocaml"
```suggestion
  "ocaml" {>= "4.08"}
```
Uses `List.filter_map` and `Fun`

2020-12-11 21:55 UTC, mseri requested changes
A few more changes, the remaining errors seems fine (missing or old C deps, timeouts, ...)

2020-12-14 09:52 UTC, mseri commented
Looks good now

2020-12-14 10:36 UTC, psafont commented
Yeah, was checking if there were some easy fixes...

- Alpine is being weird wrt linux headers
- Centos 8 changed the name for libdlm (dlm-lib)
- rrd code assumes 32-bit ints.

2020-12-14 23:40 UTC, mseri commented
I think the only bad one is rrd failure on ppc, everything else looks fine to me

2020-12-23 11:09 UTC, merged

2020-12-23 11:09 UTC, avsm commented
Can fix the ppc errors asynchronously, thanks for this!