new file:   packages/molenc/molenc.16.0.0/opam
ocaml/opam-repository pull request #18840
Opened 2021-06-10 01:18 UTC by UnixJunkie

2021-06-11 00:58 UTC, kit-ty-kate requested changes
Could you improve the minimum requirements? Feel free to use our CI for that.

2021-06-11 00:58 UTC, kit-ty-kate commented on packages/molenc/molenc.16.0.0/opam
> +  "batteries"
```suggestion
  "batteries" {>= "3.0.0"}
```
This package is using `BatString.split_on_string`

2021-06-11 00:58 UTC, kit-ty-kate commented on packages/molenc/molenc.16.0.0/opam
> +  "cpm"
```suggestion
  "cpm" {>= "4.0.0"}
```
cpm < 4.0.0 did not have the module `Cpm`

2021-06-11 00:58 UTC, kit-ty-kate commented on packages/molenc/molenc.16.0.0/opam
> +  "bst"
```suggestion
  "bst" {>= "2.0.0"}
```
Uses `Bst.Make` with only one parameter instead of two.

2021-06-11 01:02 UTC, UnixJunkie commented
I approved all your version constraints, thanks.
What do you mean by minimum requirements? Is it something else?

2021-06-11 14:26 UTC, kit-ty-kate commented
> I approved all your version constraints, thanks.
> What do you mean by minimum requirements? Is it something else?

I meant just looking out for further failures. I didn't test it entirely locally, I was only reading the CI failures but other failures were hidden by the previous ones.

2021-06-13 00:01 UTC, merged

2021-06-13 00:02 UTC, kit-ty-kate commented
Thanks! Could you return the additional fixes to the opam file upstream?

2021-06-14 00:37 UTC, UnixJunkie commented
Yes, I will upstream the version constraints you added.
Thanks.