Package monorobot.0.1
ocaml/opam-repository pull request #20163
Opened 2021-12-07 01:22 UTC by yasunariw

### `monorobot.0.1`
Notification bot for monorepos
Notification bot to handle webhook events and post notifications to Slack.

---
* Homepage: https://github.com/ahrefs/monorobot
* Source repo: git+https://github.com/ahrefs/monorobot.git
* Bug tracker: https://github.com/ahrefs/monorobot/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

2021-12-07 02:07 UTC, kit-ty-kate requested changes
Could you add the missing lower-bound constraints:
```
#=== ERROR while compiling monorobot.0.1 ======================================#
# context              2.1.1 | linux/x86_64 | ocaml-base-compiler.4.03.0 | pinned(https://github.com/ahrefs/monorobot/archive/0.1.tar.gz)
# path                 ~/.opam/4.03/.opam-switch/build/monorobot.0.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p monorobot
# exit-code            1
# env-file             ~/.opam/log/monorobot-35658-00e5e2.env
# output-file          ~/.opam/log/monorobot-35658-00e5e2.out
### output ###
#  gen_version src/version.ml
# fatal: not a git repository (or any parent up to mount point /)
# Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
# File "src/dune", line 2, characters 47-58:
# 2 |  (libraries lib base base.caml cmdliner devkit devkit.core extlib lwt.unix
#                                                    ^^^^^^^^^^^
# Error: Library "devkit.core" not found.
# Hint: try:
#   dune external-lib-deps --missing --no-config --root . --ignore-promoted-rules --default-target @install --always-show-command-line --promote-install-files --release --only-packages monorobot -p monorobot --profile release @install

- File "src/dune", line 2, characters 47-58:
- 2 |  (libraries lib base base.caml cmdliner devkit devkit.core extlib lwt.unix
-                                                    ^^^^^^^^^^^
- Error: Library "devkit.core" not found.
- Hint: try:
-   dune external-lib-deps --missing --no-config --root . --ignore-promoted-rules --default-target @install --always-show-command-line --promote-install-files --release --only-packages monorobot -p monorobot --profile release @install
```
```
#=== ERROR while compiling monorobot.0.1 ======================================#
# context              2.1.1 | linux/x86_64 | ocaml-base-compiler.4.05.0 | pinned(https://github.com/ahrefs/monorobot/archive/0.1.tar.gz)
# path                 ~/.opam/4.05/.opam-switch/build/monorobot.0.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p monorobot
# exit-code            1
# env-file             ~/.opam/log/monorobot-33735-63d443.env
# output-file          ~/.opam/log/monorobot-33735-63d443.out
### output ###
# File "/home/opam/.opam/4.05/lib/ppx_inline_test/ppx_inline_test.dune", line 1, characters 0-0:
# Warning: .dune files are ignored since 2.0. Reinstall the library with dune
# >= 2.0 to get rid of this warning and enable support for the subsystem this
# library provides.
# File "/home/opam/.opam/4.05/lib/ppx_expect/ppx_expect.dune", line 1, characters 0-0:
# Warning: .dune files are ignored since 2.0. Reinstall the library with dune
# >= 2.0 to get rid of this warning and enable support for the subsystem this
# library provides.
#  gen_version src/version.ml
# fatal: not a git repository (or any parent up to mount point /)
# Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
#       ocamlc lib/.lib.objs/byte/lib__Atd_adapters.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.05/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.lib.objs/byte -I /home/opam/.opam/4.05/lib/atdgen -I /home/opam/.opam/4.05/lib/atdgen-runtime -I /home/opam/.opam/4.05/lib/base -I /home/opam/.opam/4.05/lib/base/caml -I /home/opam/.opam/4.05/lib/base64 -I /home/opam/.opam/4.05/lib/biniou -I /home/opam/.opam/4.05/lib/cstruct -I /home/opam/.opam/4.05/lib/curl -I /home/opam/.opam/4.05/lib/devkit -I /home/opam/.opam/4.05/lib/devkit/core -I /home/opam/.opam/4.05/lib/extlib -I /home/opam/.opam/4.05/lib/hex -I /home/opam/.opam/4.05/lib/lwt -I /home/opam/.opam/4.05/lib/lwt/unix -I /home/opam/.opam/4.05/lib/nocrypto -I /home/opam/.opam/4.05/lib/omd -I /home/opam/.opam/4.05/lib/re2 -I /home/opam/.opam/4.05/lib/stdio -I /home/opam/.opam/4.05/lib/uri -I /home/opam/.opam/4.05/lib/yojson -no-alias-deps -open Lib -o lib/.lib.objs/byte/lib__Atd_adapters.cmo -c -impl lib/atd_adapters.pp.ml)
# File "lib/atd_adapters.ml", line 26, characters 16-37:
# Error: Exception patterns must be at the top level of a match case.
#       ocamlc lib/.lib.objs/byte/lib__Github.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.05/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.lib.objs/byte -I /home/opam/.opam/4.05/lib/atdgen -I /home/opam/.opam/4.05/lib/atdgen-runtime -I /home/opam/.opam/4.05/lib/base -I /home/opam/.opam/4.05/lib/base/caml -I /home/opam/.opam/4.05/lib/base64 -I /home/opam/.opam/4.05/lib/biniou -I /home/opam/.opam/4.05/lib/cstruct -I /home/opam/.opam/4.05/lib/curl -I /home/opam/.opam/4.05/lib/devkit -I /home/opam/.opam/4.05/lib/devkit/core -I /home/opam/.opam/4.05/lib/extlib -I /home/opam/.opam/4.05/lib/hex -I /home/opam/.opam/4.05/lib/lwt -I /home/opam/.opam/4.05/lib/lwt/unix -I /home/opam/.opam/4.05/lib/nocrypto -I /home/opam/.opam/4.05/lib/omd -I /home/opam/.opam/4.05/lib/re2 -I /home/opam/.opam/4.05/lib/stdio -I /home/opam/.opam/4.05/lib/uri -I /home/opam/.opam/4.05/lib/yojson -no-alias-deps -open Lib -o lib/.lib.objs/byte/lib__Github.cmo -c -impl lib/github.pp.ml)
# File "lib/github.ml", line 139, characters 8-55:
# Error: Exception patterns must be at the top level of a match case.
```
```
#=== ERROR while compiling monorobot.0.1 ======================================#
# context              2.1.1 | linux/x86_64 | ocaml-base-compiler.4.11.2 | pinned(https://github.com/ahrefs/monorobot/archive/0.1.tar.gz)
# path                 ~/.opam/4.11/.opam-switch/build/monorobot.0.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p monorobot
# exit-code            1
# env-file             ~/.opam/log/monorobot-37918-32441b.env
# output-file          ~/.opam/log/monorobot-37918-32441b.out
### output ###
#  gen_version src/version.ml
# fatal: not a git repository (or any parent up to mount point /)
# Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
# File "src/dune", line 5, characters 7-14:
# 5 |   (pps lwt_ppx))
#            ^^^^^^^
# Error: Ppx dependency on a non-ppx library "lwt_ppx". If "lwt_ppx" is in fact
# a ppx rewriter library, it should have (kind ppx_rewriter) in its dune file.

- File "src/dune", line 5, characters 7-14:
- 5 |   (pps lwt_ppx))
-            ^^^^^^^
- Error: Ppx dependency on a non-ppx library "lwt_ppx". If "lwt_ppx" is in fact
- a ppx rewriter library, it should have (kind ppx_rewriter) in its dune file.
```
```
#=== ERROR while compiling monorobot.0.1 ======================================#
# context              2.1.1 | linux/x86_64 | ocaml-base-compiler.4.13.1 | pinned(https://github.com/ahrefs/monorobot/archive/0.1.tar.gz)
# path                 ~/.opam/4.13/.opam-switch/build/monorobot.0.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p monorobot
# exit-code            1
# env-file             ~/.opam/log/monorobot-36586-73323a.env
# output-file          ~/.opam/log/monorobot-36586-73323a.out
### output ###
# File "lib/dune", line 3, characters 19-33:
# 3 |  (libraries atdgen atdgen-runtime base base64 base.caml biniou cstruct curl curl.lwt
#                        ^^^^^^^^^^^^^^
# Error: Library "atdgen-runtime" not found.
# Hint: try:
#   dune external-lib-deps --missing -p monorobot @install
```

2021-12-07 02:07 UTC, kit-ty-kate commented on packages/monorobot/monorobot.0.1/opam
> +synopsis: "Notification bot for monorepos"
```suggestion
license: "<insert your license here>"
synopsis: "Notification bot for monorepos"
```

2021-12-07 02:07 UTC, kit-ty-kate commented on packages/monorobot/monorobot.0.1/opam
> +build: ["dune" "build" "-p" name]
```suggestion
build: ["dune" "build" "-p" name "-j" jobs]
```
Without it, setting the maxiumum amount of jobs in opam would not work.

2021-12-07 02:12 UTC, kit-ty-kate commented on packages/monorobot/monorobot.0.1/opam
> + "ocamlformat" {dev}
```suggestion
```
I’m not seeing any use of ocamlformat during the compilation. If what you want is to automatically install what you use personally you can always have a custom makefile rule or similar other script to install everything you use.

2021-12-08 09:07 UTC, mseri commented on packages/monorobot/monorobot.0.1/opam
> + "base64"
```suggestion
 "base64" {>= "3.0.0"}
```

This is where the Base64 module was introduced (code uses Base64.decode_exn)

2021-12-08 09:20 UTC, mseri commented on packages/monorobot/monorobot.0.1/opam
> + "lwt"
```suggestion
 "lwt" {>= "5.1.0"}
```

Code uses Lwt.all

2021-12-08 09:45 UTC, mseri commented on packages/monorobot/monorobot.0.1/opam
> + "base" {>= "v0.12.0"}
```suggestion
 "base" {>= "v0.13.0"}
```

Uses List.drop_last_exn

2021-12-08 09:47 UTC, mseri commented
I am not sure what lower bound you need for
```
#=== ERROR while compiling monorobot.0.1 ======================================#
# context              2.1.1 | linux/x86_64 | ocaml-base-compiler.4.10.2 | pinned(https://github.com/ahrefs/monorobot/archive/0.1.tar.gz)
# path                 ~/.opam/4.10/.opam-switch/build/monorobot.0.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p monorobot -j 31
# exit-code            1
# env-file             ~/.opam/log/monorobot-36416-4ad04e.env
# output-file          ~/.opam/log/monorobot-36416-4ad04e.out
### output ###

[...]
# File "/home/opam/.opam/4.10/lib/ppx_derivers/ppx_derivers.dune", line 1, characters 0-0:
# Warning: .dune files are ignored since 2.0. Reinstall the library with dune
# >= 2.0 to get rid of this warning and enable support for the subsystem this
# library provides.
#  gen_version src/version.ml
# fatal: not a git repository (or any parent up to mount point /)
# Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
#       ocamlc src/.monorobot.eobjs/byte/dune__exe__Monorobot.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.monorobot.eobjs/byte -I /home/opam/.opam/4.10/lib/base -I /home/opam/.opam/4.10/lib/base/caml -I /home/opam/.opam/4.10/lib/cmdliner -I /home/opam/.opam/4.10/lib/devkit -I /home/opam/.opam/4.10/lib/devkit/core -I /home/opam/.opam/4.10/lib/extlib -I /home/opam/.opam/4.10/lib/lwt -I /home/opam/.opam/4.10/lib/lwt/unix -I /home/opam/.opam/4.10/lib/stdio -I /home/opam/.opam/4.10/lib/uri -I lib/.lib.objs/byte -I lib/.lib.objs/native -no-alias-deps -open Dune__exe -o src/.monorobot.eobjs/byte/dune__exe__Monorobot.cmo -c -impl src/monorobot.pp.ml)
# File "src/monorobot.ml", line 105, characters 19-43:
# 105 |   let term = Term.(const http_server_action $ addr $ port $ config $ secrets $ state) in
#                          ^^^^^^^^^^^^^^^^^^^^^^^^
# Error: This expression has type
#          unit ->
#          string ->
#          int -> Base.string -> Base.string -> Base.string option -> unit
#        but an expression was expected of type ('a -> 'b) Cmdliner.Term.t
```

2021-12-09 12:56 UTC, mseri commented
The remaining issue is due to ocamlnet being incompatible with multicore and was fixed separately. This is good to merge.

@yasunariw please port all the fixes to your upstream development branch

2021-12-09 12:56 UTC, merged

2021-12-09 13:41 UTC, yasunariw commented
Thanks @mseri @kit-ty-kate for assistance! Fixes ported upstream.