[new release] bimage, bimage-unix, bimage-io and bimage-display (0.5.0)
ocaml/opam-repository pull request #20274
Opened 2021-12-17 01:50 UTC by zshipko

A simple, efficient image-processing library

- Project page: <a href="https://github.com/zshipko/ocaml-bimage">https://github.com/zshipko/ocaml-bimage</a>
- Documentation: <a href="https://zshipko.github.io/ocaml-bimage/doc">https://zshipko.github.io/ocaml-bimage/doc</a>

##### CHANGES:

- Removed `Bimage_unix.Thread.Filter`
- Renamed `Bimage_unix.{Data_unix,Image_unix}.create_mmap` to `mmap`
- Removed `Filter.Make`, `FILTER` and `bimage-lwt`

2021-12-17 19:15 UTC, mseri commented
I think you should use `available: os = "linux"` instead of constraining ocaml

2021-12-17 19:16 UTC, mseri requested changes

2021-12-17 19:16 UTC, mseri commented on packages/bimage-display/bimage-display.0.5.0/opam
> +    "ocaml" {>= "4.08.0" & os = "linux"}
```suggestion
    "ocaml" {>= "4.08.0"}
```

2021-12-17 19:16 UTC, mseri commented on packages/bimage-display/bimage-display.0.5.0/opam
> +url {
```suggestion

available: os = "linux"

url {
```

2021-12-17 19:16 UTC, mseri commented on packages/bimage-io/bimage-io.0.5.0/opam
> +    "ocaml" {>= "4.08.0" & os = "linux"}
```suggestion
    "ocaml" {>= "4.08.0"}
```

2021-12-17 19:16 UTC, mseri commented on packages/bimage-io/bimage-io.0.5.0/opam
> +url {
```suggestion

available: os = "linux"

url {
```

2021-12-17 19:18 UTC, zshipko commented
Thanks! I knew there was something like that but couldn't remember the syntax

2021-12-22 09:57 UTC, mseri commented
Thanks

2021-12-22 09:58 UTC, merged