core_unix v0.15.2
ocaml/opam-repository pull request #22305
Opened 2022-10-17 21:39 UTC by tov

OCaml 5 support

2022-10-18 08:17 UTC, mseri commented
This one looks fine

2022-10-18 12:00 UTC, kit-ty-kate requested changes

2022-10-18 12:00 UTC, kit-ty-kate commented on packages/core_unix/core_unix.v0.15.2/opam
> +src: "https://github.com/janestreet/core_unix/archive/refs/tags/v0.15.1.tar.gz"
```suggestion
src: "https://github.com/janestreet/core_unix/archive/refs/tags/v0.15.2.tar.gz"
```
Why is this 0.15.1?

2022-10-19 11:05 UTC, kit-ty-kate approved these changes

2022-10-19 11:05 UTC, merged