Package prooftree.0.14
ocaml/opam-repository pull request #25334
Opened 2024-02-23 16:47 UTC by hendriktews

### `prooftree.0.14`
Proof-tree visualization for Coq via Proof General
Prooftree visualizes proof trees during proof development in Coq with
Proof General. Prooftree helps against getting lost between different
subgoals in interactive proof development. It clearly shows where the
current subgoal comes from and thus helps in developing the right plan
for solving it.

---
* Homepage: http://askra.de/software/prooftree/
* Source repo: git+https://github.com/hendriktews/prooftree.git
* Bug tracker: https://github.com/hendriktews/prooftree/issues

---
:camel: Pull-request generated by opam-publish v2.3.0

2024-02-26 22:00 UTC, haochenx requested changes
other than the inline comments, this PR looks good to me

2024-02-26 22:00 UTC, haochenx commented on packages/prooftree/prooftree.0.14/opam
> +dev-repo: "git+https://github.com/hendriktews/prooftree.git"
seems like a typo
```suggestion
dev-repo: "git+https://github.com/hendriktews/proof-tree.git"
```

2024-02-26 22:00 UTC, haochenx commented on packages/prooftree/prooftree.0.14/opam
> +bug-reports: "https://github.com/hendriktews/prooftree/issues"
seems like a typo
```suggestion
bug-reports: "https://github.com/hendriktews/proof-tree/issues"
```

2024-02-26 22:00 UTC, haochenx commented on packages/prooftree/prooftree.0.14/opam
> +homepage: "http://askra.de/software/prooftree/"
It's entirely up to you, but HTTPS is probably better for the sake of security
```suggestion
homepage: "https://askra.de/software/prooftree/"
```

2024-02-27 11:02 UTC, mseri commented
Thanks. Please upstream the fixes to your opam file

2024-02-27 11:02 UTC, merged

2024-02-28 10:00 UTC, hendriktews commented
Done, thanks.