ocamlbuild for windows OCaml 5.2
ocaml/opam-repository pull request #25939
Opened 2024-05-26 13:56 UTC by hhugo

This PR provides a windows variant of ocamlbuild.0.14.3.
It re-uses the patch used to fix ocamlbuild.0.14.2 for windows and make ocamlbuild.0.14.3 available on windows with OCaml 5.02.

2024-05-26 13:57 UTC, hhugo commented
cc @kit-ty-kate @gasche

2024-05-27 09:11 UTC, hhugo commented
I've tested this in https://github.com/ocsigen/js_of_ocaml/pull/1615

2024-05-27 11:45 UTC, kit-ty-kate requested changes
I'd rather avoid having a separate package for this.
I think we should either have the patch applied conditionally on Windows in the 0.14.3 package or wait a couple weeks to have an upstream version (this is next on my todo-list after the release of opam 2.2.0~rc1)

2024-05-27 13:40 UTC, hhugo commented
> I'd rather avoid having a separate package for this. I think we should either have the patch applied conditionally on Windows in the 0.14.3 package or wait a couple weeks to have an upstream version (this is next on my todo-list after the release of opam 2.2.0~rc1)

I don't think we should wait before making ocamlbuild available on windows 5.2. There are enough issues on the windows side already.

We could make it part of the main opam file. I don't know the rational for splitting the files initially. I just kept the setup in place to unlock the situation as fast as possible.

2024-05-28 00:16 UTC, hhugo commented
I think it would be enough to merge this into https://github.com/ocaml-opam/opam-repository-mingw

Maybe we should move ocamlbuild.0.14.2+win as well. What do you think ?

2024-05-28 12:17 UTC, kit-ty-kate commented
> Maybe we should move ocamlbuild.0.14.2+win as well. What do you think ?

Packages can't be removed until https://github.com/ocaml/opam-repository/issues/23789 is implemented/formally accepted.

But overall I think it would be fine as part of the main opam file. I really don't understand why it was split in the first place.
It would just be a case of doing:
```
patches: [
  "ocamlbuild-0.14.2.patch" {os = "win32"}
]
```

2024-05-28 12:30 UTC, hhugo commented
> > Maybe we should move ocamlbuild.0.14.2+win as well. What do you think ?
> 
> Packages can't be removed until #23789 is implemented/formally accepted.
> 
> But overall I think it would be fine as part of the main opam file. I really don't understand why it was split in the first place. It would just be a case of doing:
> 
> ```
> patches: [
>   "ocamlbuild-0.14.2.patch" {os = "win32"}
> ]
> ```

I guess the `+win` variant makes it clear that it's a modified version. There are a fair amount of changes in this patch. Changes that have never been reviewed or proposed upstream.

2024-05-28 12:31 UTC, hhugo commented
That said, if you prefer to merge the patch in the main opam, it's fine.

2024-06-01 21:55 UTC, hhugo commented
Can we unlock the situation on windows and merge this ?

2024-06-03 07:59 UTC, merged

2024-06-03 07:59 UTC, mseri commented
Done. Is there any chance this patch could be reviewed and merged into upstream ocamlbuild any time soon? Windows support shouldn't be an ad-hoc opam-repo thing imho

2024-06-03 10:02 UTC, gasche commented
The problem is that this patch is a hodge-podge of stuff that was only ever tested on Windows, so it feels very unsafe (to me) to merge as-is for everyone. Just splitting this into proper patches and understanding the intent of each change is a substantial amount of work. In principle I would be delighted to see this work being done, but in practice few people have the energy to do it. @hhugo has done some of it in the last few weeks, and we try to make his contributions as pleasant as possible to keep him motivated to do more :-)