Update bitstring sources
ocaml/opam-repository pull request #26074
Opened 2024-06-12 17:34 UTC by CharlesAverill

Old versions of the `bitstring` package pointed their source to a now-defunct Bitbucket repository. This PR updates the sources to the currently-maintained Github repository https://github.com/xguerin/bitstring

2024-06-13 09:22 UTC, mseri commented
Looks like some checksums are different. We should try to get the old packages from the caches: https://github.com/ocaml/opam-repository/wiki/FAQ#how-to-find-lost-archives-of-packages

2024-07-23 17:10 UTC, shonfeder commented on packages/bitstring/bitstring.2.1.0/opam
> +  src: "https://github.com/xguerin/bitstring/archive/v2.1.0.tar.gz"
@mseri I was not able to find this source in any of the archives using the recipes in https://github.com/ocaml/opam-repository/wiki/FAQ#how-to-find-lost-archives-of-packages

E.g., I've tried

- https://opam.robur.coop/cache/sha256/a8/a848f15787709e88bf97a81d5e7dc0115ad83b3cf36bbaec6a69fdf3d102f7bd
- https://opam.ocaml.org/cache/sha256/a8/a848f15787709e88bf97a81d5e7dc0115ad83b3cf36bbaec6a69fdf3d102f7bd
- https://opam.ocaml.org/cache/md5/70/70f7acebe337072bff03a1f7a3fb1d3a

Do we have any other option (or might I be making a mistake with with the construction of the URLs)? Or will we need to accept a changed checksum if this is to remain available?

2024-07-31 19:11 UTC, shonfeder requested changes

2024-07-31 19:11 UTC, shonfeder commented on packages/bitstring/bitstring.2.1.0/opam
> +  src: "https://github.com/xguerin/bitstring/archive/v2.1.0.tar.gz"
Thanks to @kit-ty-kate, I persisted and found a source via the md5 has on ocamlpro's cache:

```suggestion
  src: "https://gitlab.ocamlpro.com/OCamlPro/opam-repository/-/raw/cached/cache/md5/70/70f7acebe337072bff03a1f7a3fb1d3a"
```

https://gitlab.ocamlpro.com/OCamlPro/opam-repository/-/raw/cached/cache/md5/70/70f7acebe337072bff03a1f7a3fb1d3a

2024-07-31 19:11 UTC, shonfeder commented on packages/bitstring/bitstring.2.1.1/opam
> +  src: "https://github.com/xguerin/bitstring/archive/v2.1.1.tar.gz"
```suggestion
  src: "https://gitlab.ocamlpro.com/OCamlPro/opam-repository/-/raw/cached/cache/md5/69/69797ac391a4c4a106bbde2a2bc8d9ab"
```

https://gitlab.ocamlpro.com/OCamlPro/opam-repository/-/raw/cached/cache/md5/69/69797ac391a4c4a106bbde2a2bc8d9ab

2024-07-31 19:11 UTC, shonfeder commented on packages/bitstring/bitstring.3.0.0/opam
> +  src: "https://github.com/xguerin/bitstring/archive/v3.0.0.tar.gz"
```suggestion
  src: "https://gitlab.ocamlpro.com/OCamlPro/opam-repository/-/raw/cached/cache/md5/ce/ce1d3b99ed9d4ff98af1fafd9274d897"
```

https://gitlab.ocamlpro.com/OCamlPro/opam-repository/-/raw/cached/cache/md5/ce/ce1d3b99ed9d4ff98af1fafd9274d897

2024-07-31 19:11 UTC, shonfeder commented on packages/bitstring/bitstring.3.1.0/opam
> +  src: "https://github.com/xguerin/bitstring/archive/v3.1.0.tar.gz"
```suggestion
  src: "https://gitlab.ocamlpro.com/OCamlPro/opam-repository/-/raw/cached/cache/md5/22/22807a9517ede34823ebdb36d6bacef8"
```

https://gitlab.ocamlpro.com/OCamlPro/opam-repository/-/raw/cached/cache/md5/22/22807a9517ede34823ebdb36d6bacef8

2024-07-31 19:11 UTC, shonfeder commented on packages/bitstring/bitstring.3.1.1/opam
> +  src: "https://github.com/xguerin/bitstring/archive/v3.1.1.tar.gz"
```suggestion
  src: "https://gitlab.ocamlpro.com/OCamlPro/opam-repository/-/raw/cached/cache/md5/eb/ebf52fe55946c70aa7cb3fe51905b830"
```

https://gitlab.ocamlpro.com/OCamlPro/opam-repository/-/raw/cached/cache/md5/eb/ebf52fe55946c70aa7cb3fe51905b830

2024-07-31 19:28 UTC, kit-ty-kate commented
those archives should probably be uploaded to https://github.com/ocaml/opam-source-archives/ instead of relying on ocamlpro's repository

2024-07-31 23:01 UTC, shonfeder commented
Ah ok, makes sense. I'll do that when I have a moment.

Could you (or someone with perms) update https://github.com/ocaml/opam-repository/wiki/FAQ#how-to-find-lost-archives-of-packages so that the need for adding the sources to the archive in such cases is recorded?

2024-08-01 10:19 UTC, mseri commented
Done

2024-08-07 13:25 UTC, mseri commented on packages/bitstring/bitstring.2.1.0/opam
> +  src: "https://github.com/xguerin/bitstring/archive/v2.1.0.tar.gz"
```suggestion
  src: "https://github.com/ocaml/opam-source-archives/raw/main/bitstring.2.1.0.tar.gz"
```

2024-08-07 13:25 UTC, mseri commented on packages/bitstring/bitstring.2.1.1/opam
> +  src: "https://github.com/xguerin/bitstring/archive/v2.1.1.tar.gz"
```suggestion
  src: "https://github.com/ocaml/opam-source-archives/raw/main/bitstring.2.1.0.tar.gz"
```

2024-08-07 13:40 UTC, merged

2024-08-07 13:40 UTC, mseri commented
Sources are now all accessible

2024-08-07 16:25 UTC, shonfeder commented
Thanks for picking this up!