[new release] ppx_heml (0.1.0)
ocaml/opam-repository pull request #26297
Opened 2024-07-27 07:08 UTC by pjlast

PPX for deriving HTML templates

- Project page: <a href="https://github.com/pjlast/heml">https://github.com/pjlast/heml</a>

##### CHANGES:

* Initial release

2024-07-27 08:10 UTC, pjlast commented
Seems like the only error left is "Possible conflict with `ppx_here` and `ppx_demo`" 🤷‍♂️

2024-07-27 20:54 UTC, shonfeder requested changes
Thank you for publishing this package! It looks quite useful :)

> Seems like the only error left is "Possible conflict with `ppx_here` and `ppx_demo`" 🤷‍♂️

Those are not an issue (and rather indicate our conflict checking is still too coarse).

Just two small changes requested to get it in great shape, afaict.

2024-07-27 20:54 UTC, shonfeder commented on packages/ppx_heml/ppx_heml.0.1.0/opam
> +tags: ["topics" "to describe" "your" "project"]
Would you either remove the tags or change them to be relevant?

2024-07-27 20:54 UTC, shonfeder commented on packages/ppx_heml/ppx_heml.0.1.0/opam
> +maintainer: ["Petri-Johan Last"]
Could you provide a contact for maintenance? An email address is what we usually use and is preferable, but it should be some way you can be contacted at least.

2025-03-20 14:52 UTC, mseri commented on packages/ppx_heml/ppx_heml.0.1.0/opam
> +tags: ["topics" "to describe" "your" "project"]
```suggestion
```

2025-03-20 14:54 UTC, mseri commented
@pjlast this is waiting for some very small changes

Given the lack of activity I am going to close this, but please feel free to reopen it or submit a new one with the fixes. The library seems quite interesting and we'd be happy to merge.

2025-03-20 14:54 UTC, closed without merging